version: "2.3"

services:
  xanomaly:
    image: ghcr.io/sifis-home/xanomaly:latest
    restart: always

  watchtower:
    image: containrrr/watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  