#  ____  _   _  ___ _     ____
# | __ )| | | ||_ _| |   |  _ \
# |  _ \| | | | | || |   | | | |
# | |_) | |_| | | || |___| |_| |
# |____/ \___/ |___|_____|____/

name: xAnomaly
run-name: Official build started by ${{ github.actor }}
on:
  push:
    branches:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub container registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/sifis-home/xanomaly:latest
          build-args: |
            COMMIT_ID=${{ github.sha }}
